### ISSUE TITLE
Match this with client-side features to communicate with Lambda, and more.

### ISSUE THREAD

**Issue by marcglasberg** [awslabs/aws-lambda-dart-runtime#12]
This is really amazing for the server side. Congrats to AWS for finally acknowledging the existence of Flutter. However, for AWS to really be able to compete with Firebase in Flutter, you need a few more things in the CLIENT-SIDE:

• Auth (Cognito) ➜ So that the lambda can authenticate the users.

• An easier way to send/receive Json to Lambda (a few functions to use instead of forcing people to manually use https).

• AppSync ➜ This one is the most important for you to compete with Firebase. We need realtime. It may use Platform Channels, but it would be perfect if it were all done in Dart.

• An easier way to send files to S3. (a few functions to use instead of forcing people to manually use https).

**Comment by katallaxie** [comment]
👋 Marc,

Thanks for your input. These are all very valuable ideas, but they are beyond the scope of this project. I have collected your ideas and will pass them on to the respective service team owners.

Stay tuned 📻 , but closing this ticket now.
