### ISSUE TITLE
AwsApiGatewayEventHeaders does not pass through custom headers

### ISSUE THREAD

**Issue by kmcgill88** [awslabs/aws-lambda-dart-runtime#13]
This package has been working great for me in prod! I ran into a use case today that I thought could be improvd. [AwsApiGatewayEventHeaders](https://github.com/awslabs/aws-lambda-dart-runtime/blob/master/lib/events/apigateway_event.dart#L120) is parsing some standard headers  like `userAgent`. This is great however I can not get access to custom headers or even simple caching headers like `If-None-Match`.

Would it be possible to add `raw` or `rawHeaders` (naming is hard) to `AwsApiGatewayEventHeaders`? This would expose a way to access any possible header that comes through while keeping the existing functionality.

Example:
```dart
event.headers.raw['x-my-custom-header']

or 

event.headers.raw.contains('x-my-custom-header')
```
`raw` here being the entire headers map.

**Comment by kmcgill88** [comment]
@katallaxie Can you please cut a new release with this in it?

**Comment by katallaxie** [comment]
@kmcgill88 `1.0.3+1` is published.
