### ISSUE TITLE
Publish on pub.dev

### ISSUE THREAD

**Issue by shinayser** [awslabs/aws-lambda-dart-runtime#2]
First of all THANKYOU for such amazing repository. 

There is any reason for why this project isn't listed on pub.dev?
Pub is the dart's official package repository and is often used by other companies to search for the capabilities of a language. Having an AWS Lambda support there would be a great showcase for the language.

**Comment by katallaxie** [comment]
We are working on getting it published.

**Comment by kmcgill88** [comment]
🎉  It's published! https://pub.dev/packages/aws_lambda_dart_runtime

Looks like this issue can be closed.

**Comment by shinayser** [comment]
AMAZING JOB!
